"""create_notepad_model

Revision ID: 0ad2b5f6f303
Revises: 8947d8660461
Create Date: 2024-10-21 10:57:03.126188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad2b5f6f303'
down_revision = '8947d8660461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notepad', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
